import MainHeader from "@/components/main-header/main-header";
import "../styles/globals.css";


export const metadata = {
	title: "Prodcuts",
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<MainHeader />
				{children}
			</body>
		</html>
	);
};
